#pragma once

#if __has_include("config_private.h")
#include "config_private.h"
#endif

#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif

#ifndef WIFI_SSID_2
#define WIFI_SSID_2 ""
#endif

#ifndef WIFI_PASSWORD_2
#define WIFI_PASSWORD_2 ""
#endif

#define AP_SSID "StackChan-Direct"
#define AP_PASSWORD "stackchan123"
#define AP_IP_0 192
#define AP_IP_1 168
#define AP_IP_2 4
#define AP_IP_3 1

#define WS_PORT 8080
#define WS_PATH "/"

#define FACE_IDLE_PATH "/idle.png"
#define FACE_LISTEN_PATH "/listen.png"
#define FACE_TALK_0_PATH "/talk_0.png"
#define FACE_TALK_1_PATH "/talk_1.png"
#define FACE_BAD_0_PATH "/bad_0.png"
#define FACE_BAD_1_PATH "/bad_1.png"
#define FACE_GOOD_0_PATH "/good_0.png"
#define FACE_GOOD_1_PATH "/good_1.png"
#define FACE_GOOD_BLINK_PATH "/good_blink.png"
#define FACE_PHOTO_0_PATH "/photo_0.png"
#define FACE_PHOTO_1_PATH "/photo_1.png"
#define FACE_PHOTO_BLINK_PATH "/photo_blink.png"
#define FACE_PHOTO_BLINK_TALK_PATH "/photo_blink_talk.png"
#define FACE_PHOTO_MASTER_0_PATH "/photo_master_0.png"
#define FACE_PHOTO_MASTER_1_PATH "/photo_master_1.png"
#define FACE_NADENADE_0_PATH "/nadenade_0.png"
#define FACE_NADENADE_1_PATH "/nadenade_1.png"
#define FACE_FURIFURI_0_PATH "/furifuri_0.png"
#define FACE_FURIFURI_1_PATH "/furifuri_1.png"
#define FACE_BLINK_PATH "/blink.png"
#define FACE_SMILE_PATH "/smile.png"

#define FACE_IMAGE_WIDTH 240
#define FACE_IMAGE_HEIGHT 240

#define LIP_SYNC_INTERVAL_MS 150
#define BLINK_MIN_INTERVAL_MS 3000
#define BLINK_MAX_INTERVAL_MS 7000
#define BLINK_DURATION_MS 120
#define IDLE_SMILE_MIN_INTERVAL_MS 8000
#define IDLE_SMILE_MAX_INTERVAL_MS 20000
#define IDLE_SMILE_DURATION_MS 1500

#define SERVO_UPDATE_INTERVAL_MS 30
#define SERVO_STEP_DEGREES 2
#define SERVO_PAN_MIN 45
#define SERVO_PAN_MAX 135
#define SERVO_TILT_MIN 60
#define SERVO_TILT_MAX 120
#define SERVO_PAN_CENTER 90
#define SERVO_TILT_CENTER 82
#define SERVO_OUTPUT_ENABLED 1
#define SERVO_OUTPUT_SPEED 500
#define SERVO_STARTUP_OUTPUT_DELAY_MS 4000
#define LISTENING_NOD_FIRST_MIN_INTERVAL_MS 1200
#define LISTENING_NOD_FIRST_MAX_INTERVAL_MS 1500
#define LISTENING_NOD_MIN_INTERVAL_MS 2100
#define LISTENING_NOD_MAX_INTERVAL_MS 4200
#define LISTENING_NOD_DOWN_MS 240
#define LISTENING_NOD_UP_MS 280
#define LISTENING_NOD_TILT_DELTA 14

#define INTERACTION_STARTUP_IGNORE_MS 4000
#define PET_TOUCH_RELEASE_GRACE_MS 1000
#define BACK_TOUCH_INTENSITY_THRESHOLD 2
#define BACK_TOUCH_REQUIRED_SAMPLES 2
#define BACK_TOUCH_STARTUP_RELEASE_MS 1000
#define PET_MOVE_MIN_INTERVAL_MS 130
#define PET_MOVE_MAX_INTERVAL_MS 280
#define PET_BIG_MOVE_CHANCE_PERCENT 38
#define PET_SMALL_PAN_MIN 10
#define PET_SMALL_PAN_MAX 22
#define PET_BIG_PAN_MIN 24
#define PET_BIG_PAN_MAX 38
#define PET_SMALL_TILT_MIN 90
#define PET_SMALL_TILT_MAX 104
#define PET_BIG_TILT_MIN 100
#define PET_BIG_TILT_MAX 116
#define SHAKE_UPDATE_INTERVAL_MS 20
#define SHAKE_ACC_THRESHOLD_G 1.1f
#define SHAKE_GYRO_THRESHOLD_DPS 280.0f
#define SHAKE_REQUIRED_SAMPLES 2
#define SHAKE_FACE_HOLD_MS 1500
#define SHAKE_COOLDOWN_MS 1800
#define SHAKE_MOTION_INTERVAL_MS 80
#define SHAKE_MOTION_PAN_MAX_DEGREES 24
#define SHAKE_MOTION_TILT_UP_DEGREES 14
#define SHAKE_MOTION_TILT_DOWN_DEGREES 18
#define SHAKE_MOTION_GYRO_PAN_SCALE 0.030f
#define SHAKE_MOTION_GYRO_TILT_SCALE 0.020f

#define AUDIO_SAMPLE_RATE 16000
#define AUDIO_CHANNELS 1
#define AUDIO_BITS_PER_SAMPLE 16
#define MIC_SEND_INTERVAL_MS 20
#define AUDIO_MIC_MAGNIFICATION 4
#define AUDIO_MIC_NOISE_FILTER_LEVEL 32
#define AUDIO_MIC_OVERSAMPLING 2
#define AUDIO_MIC_SOFTWARE_GAIN_Q8 160
#define AUDIO_MIC_CLIP_THRESHOLD 30000
#define AUDIO_CHUNK_MS 20
#define AUDIO_CHUNK_SAMPLES ((AUDIO_SAMPLE_RATE * AUDIO_CHUNK_MS) / 1000)
#define AUDIO_CHUNK_BYTES (AUDIO_CHUNK_SAMPLES * sizeof(int16_t))
#define AUDIO_PLAYBACK_CHUNK_MS 60
#define AUDIO_PLAYBACK_CHUNK_SAMPLES ((AUDIO_SAMPLE_RATE * AUDIO_PLAYBACK_CHUNK_MS) / 1000)
#define AUDIO_PLAYBACK_CHUNK_BYTES (AUDIO_PLAYBACK_CHUNK_SAMPLES * sizeof(int16_t))
#define AUDIO_MIC_BUFFER_COUNT 4
#define AUDIO_SPEAKER_BUFFER_COUNT 8
#define AUDIO_SPEAKER_CHANNEL 0
#define AUDIO_SPEAKER_VOLUME 180
#define AUDIO_PLAYBACK_PREBUFFER_MS 220
#define AUDIO_PLAYBACK_PREBUFFER_BYTES ((AUDIO_SAMPLE_RATE * AUDIO_PLAYBACK_PREBUFFER_MS / 1000) * sizeof(int16_t))
#define AUDIO_RX_RING_BYTES (512 * 1024)
#define AUDIO_IDLE_DRAIN_GRACE_MS 300
#define AUDIO_SPEAKER_TO_MIC_DELAY_MS 250
#define AUDIO_AFTER_CAPTURE_SPEAKER_DELAY_MS 250

#define HTTP_PORT 80
#define CAMERA_JPEG_QUALITY 80
